service:
  name: downloads-test-client
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

vpc:
  securityGroupIds:
    - sg-08b4e0323206d11b7
    - sg-0c554a0276d163b42
  subnetIds:
    - subnet-05c25db5a0333ce8a
    - subnet-0e2b745404eb5a656

functions:
  outage-download-test:
    handler: src/handler/downloads/handler.handler
    events:
      - http:
          method: put
          path: outages/downloads
    package:
    #   exclude:
    #     - src/**
    #     - node_modules/**
    #     - dist
    #   include:
    #     - somefile.txt
    #     - src/service-tests/download-tests.spec.ts
    #     - src/drivers/**
    #     - src/types/**
    #     - src/users.ts
    #   artifact: test-deploy/test.zip
