version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10
        
        working_directory: ~/repo
        
        steps:
            - checkout
            - run:
                name: Install Node dependencies
                command: npm install
            - run:
                name: Unit tests
                command: npm test
    
    deploy-production:
        docker:
            - image: circleci/node:10
        
        working_directory: ~/repo

        steps:
            - checkout
            - run:
                name: Install serverless dependencies
                command: npm install -g serverless
            - run:
                name: Install node dependencies
                command: npm install
            - run:
                name: Deploy to AWS
                command: npm run deploy

workflows:
    version: 2
    build-test:
        jobs:
            - build:
                filters:
                    branches:
                        ignore: /master/
    
    build-test-and-deploy-production:
        jobs:
            - build:
                filters:
                    branches:
                        only: /master/
            - deploy-production:
                requires:
                    - build
                filters:
                    branches:
                        only: /master/