version: 2.1
jobs:
    build:
        docker:
            - image: circleci/node:10
        
        working_directory: ~/repo
        
        steps:
            - checkout
            - setup_remote_docker
            - jq/install
            - run:
                name: Install node dependencies
                command: npm install
            - run:
                name: Unit tests
                command: npm test
            - run:
                name: Clone database image
                command: git clone https://$BITBUCKET_USERNAME:$BITBUCKET_PASSWORD@bitbucket.org/cyber4all-clark/database-image.git
            - run:
                name: Start Mongo
                command: |
                    docker run -p 27017:27017 -v $(pwd)/database-image/database-image-02-20-20:/data/db mongo:4
            - run:
                name: Install save KEY as ENV
                command: |
                    export KEY=$(aws ssm get-parameters --names "KEY" | jq -r '.Parameters[0].Value')
            - run:
                name: Wait 60 seconds for Mongo to be available
                command: sleep 60
            - run:
                name: Install newman and run functional tests
                command: |
                    sudo npm i -g newman
                    npm run ci
    
    deploy-production:
        docker:
            - image: circleci/node:10
        
        working_directory: ~/repo

        steps:
            - checkout
            - run:
                name: Install serverless dependencies
                command: sudo npm install -g serverless
            - run:
                name: Install node dependencies
                command: npm install
            - run:
                name: Deploy to AWS
                command: npm run deploy

orbs:
    jq: circleci/jq@1.9.1

workflows:
    version: 2.1
    build-test:
        jobs:
            - build:
                filters:
                    branches:
                        ignore: /master/
    
    build-test-and-deploy-production:
        jobs:
            - build:
                filters:
                    branches:
                        only: /master/
            - deploy-production:
                requires:
                    - build
                filters:
                    branches:
                        only: /master/